name: code-coverage
on:
  push:
    branches:
      - master
jobs:
  code-coverage:
    name: code-coverage
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: Run code coverage
        run: npm run coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
